### ISSUE TITLE
benchmark.run yields no results

### ISSUE THREAD

**Issue by asakusuma** [krisselden/chrome-tracing#5]
I took the "hello world" example in the README and created a simple usage example: https://github.com/asakusuma/chrome-tracing-example

`benchmark.run()` seems to resolve before chrome even boots, and the resolved value is `undefined`.

**Comment by krisselden** [comment]
@asakusuma the README should be updated or the iteration count should be defaulted but the primary way to run benchmarks is with the runner.

**Comment by asakusuma** [comment]
@krisselden thanks for updating the README, I tried the README sample code and it worked.
